### ISSUE TITLE
No module named 'joblib'

### ISSUE THREAD

**Issue by hellomuse** [shenweichen/GraphEmbedding#2]
请问这是什么原因？
Traceback (most recent call last):
  File "deepwalk_wiki.py", line 4, in <module>
    from ge.classify import read_node_label, Classifier
  File "//anaconda/lib/python3.5/site-packages/ge-0.0.0-py3.5.egg/ge/__init__.py", line 1, in <module>
  File "//anaconda/lib/python3.5/site-packages/ge-0.0.0-py3.5.egg/ge/models/__init__.py", line 1, in <module>
  File "//anaconda/lib/python3.5/site-packages/ge-0.0.0-py3.5.egg/ge/models/deepwalk.py", line 20, in <module>
  File "//anaconda/lib/python3.5/site-packages/ge-0.0.0-py3.5.egg/ge/walker.py", line 7, in <module>
ImportError: No module named 'joblib'

**Comment by shenweichen** [comment]
单独安装一下joblib包吧~
