### ISSUE TITLE
关于fastdtw的问题

### ISSUE THREAD

**Issue by hahaymm** [shenweichen/GraphEmbedding#44]
### Traceback (most recent call last):
  File "/Users/yangfengyu/Desktop/GraphEmbedding-master/examples/line_wiki.py", line 4, in <module>
    from ge.classify import read_node_label, Classifier
  File "/Users/yangfengyu/Desktop/GraphEmbedding-master/ge/__init__.py", line 1, in <module>
    from .models import *
  File "/Users/yangfengyu/Desktop/GraphEmbedding-master/ge/models/__init__.py", line 5, in <module>
    from .struc2vec import Struc2Vec
  File "/Users/yangfengyu/Desktop/GraphEmbedding-master/ge/models/struc2vec.py", line 28, in <module>
    from fastdtw import fastdtw
ModuleNotFoundError: No module named 'fastdtw'

我在本地进行了实验，但是一直报错如上。
请问fastdtw模块是项目内的还是第三方的库，我在项目里全局搜索没有找到。
期待回复！

**Comment by jackchenwen** [comment]
pip install fastdtw

**Comment by wzrbill** [comment]
conda -m conda-forge fastdtw
这个命令会读取该包的配置文件，并且升级（或者降级）关联的包
