### ISSUE TITLE
SDNE,'NoneType' object is not callable

### ISSUE THREAD

**Issue by orderer0001** [shenweichen/GraphEmbedding#65]
error during training：
model.train(batch_size=1024,epochs=3,verbose=2)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow24/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-0e6f80dc2faf>", line 1, in <module>
    model.train(batch_size=1024,epochs=3,verbose=2)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow24/lib/python3.8/site-packages/ge/models/sdne.py", line 129, in train
    A_train = self.A[index, :].todense()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow24/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1854, in train_on_batch
    logs = self.train_function(iterator)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow24/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow24/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 917, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
TypeError: 'NoneType' object is not callable

Does anyone have experience with this problem?

**Comment by shenweichen** [comment]
Fixed by #83.

SDNE training now uses public `tensorflow.keras` APIs, TensorFlow-native loss operations, explicit array inputs/targets, and updated batch training behavior. Closing this as resolved; please open a new issue if the error still appears in a supported Python/TensorFlow combination.
