### ISSUE TITLE
在创建图G时发生读取文件错误

### ISSUE THREAD

**Issue by through-the-valley** [shenweichen/GraphEmbedding#69]
(base) PS D:\pythontemp\gnnstudy\GraphEmbedding-master> & D:/anaconda3/python.exe d:/pythontemp/gnnstudy/GraphEmbedding-master/examples/deepwalk_wiki.py
Traceback (most recent call last):
  File "d:\pythontemp\gnnstudy\GraphEmbedding-master\examples\deepwalk_wiki.py", line 45, in <module>
    G = nx.read_edgelist('../data/wiki/Wiki_edgelist.txt',
  File "D:\anaconda3\lib\site-packages\networkx\utils\decorators.py", line 816, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 5", line 3, in argmap_read_edgelist_1
  File "D:\anaconda3\lib\site-packages\networkx\utils\decorators.py", line 189, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/wiki/Wiki_edgelist.txt'

检查了下这个文件是存在的，路径也没有修改过，其他几种算法也都是这样打不开文件，请问有人有头绪吗

**Comment by shenweichen** [comment]
Fixed by #83.

Example scripts now resolve data files relative to the project root instead of depending on the current working directory, so running scripts from the repository root should no longer fail with `../data/...` `FileNotFoundError`. Closing this as resolved.
